# Generated by Django 4.1.5 on 2023-01-24 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=255, null=True)),
                ('lastName', models.CharField(blank=True, max_length=255, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('child_at', models.CharField(blank=True, choices=[('At Bus', 'At Bus'), ('At School', 'At School'), ('At ClassRoom', 'At ClassRoom')], max_length=255, null=True)),
                ('banned_food', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChildParent', to='parent.parentprofile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChildSchool', to='school.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ChildProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChildWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_amount', models.IntegerField(default=500)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ChildWallet', to='child.childprofile')),
            ],
        ),
    ]
