# Generated by Django 4.1.5 on 2023-01-24 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_alter_childprofile_banned_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildDaysOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ChildDayOff', to='child.childprofile')),
            ],
        ),
    ]
