# Generated by Django 4.1.5 on 2023-01-24 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_childdaysoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdaysoff',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChildDayOff', to='child.childprofile'),
        ),
    ]
